### PR TITLE
A non-concurrent pool

### PR DESCRIPTION
**Pull request by CQQL**
This PR implements a non-concurrent pool under the name of `Futuroscope::Pools::NoPool`.

It is useful for testing. I am using [hyperclient](https://github.com/codegram/hyperclient) with [faradays rack adapter](https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/rack.rb) to test a HAL API. And from normal rails testing, I am used to the test server running in the same thread as the tests. This has the huge advantage, `ActiveRecord` in the tests and in the rack app share the same database connection, so that tests can run in a transaction and clean up is a simple rollback. This does not work anymore, when throwing threads in the mix, because ActiveRecord will reconnect and you have to actually write to the database and use `database_cleaner` for cleanup. The cleanup is really expensive though. A single integration test goes from 0.5 seconds to 4.5 seconds.

The last commit unifies the use of `'` and `"` by replacing all `'` with `"`. If you don't like it, you can of course omit it, but it kept catching my eye.

### CODE REVIEW

**Comment by txus** [comment]
@CQQL Thanks for your contribution. I'll take some time next week to rethink the compatibility matrix (we're dropping support for 1.9) and fix the Rubinius issues. :)

**Comment by CQQL** [comment]
Will you publish a new version? I just stumbled upon this again, because I just did a `bundle outdated` and saw, that we are still pulling this from my fork.

**Comment by dblock** [comment]
Bump, this came up in https://github.com/codegram/hyperclient/issues/102, a release would have saved @joshco some time.

**Comment by joshco** [comment]
Any update on this?

**Pull request merged**
